### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by harika09** [aarock1234/shopify-monitor#1]
tried to monitor this Shopify site but encountered error. 

ERROR]  INIT ERR @ https://parkaccess.com.ph: Cannot read property 'products' of undefined

**Comment by aarock1234** [comment]
This seems to happen when the password is up. My detection broke for some reason. I can fix it later but for now I don't support passwords.

I will leave this issue open until I fix it.

**Comment by aarock1234** [comment]
Fixed this in the recent update, delete all files and follow the instructions starting from step 3.
