### ISSUE TITLE
monitor for https://parkaccess.com.ph/ does not work

### ISSUE THREAD

**Issue by lorenzosab** [aarock1234/shopify-monitor#12]
monitor for https://parkaccess.com.ph/ does not work
it just shows this:
[21:15:14.624] [LOG]    Monitor Started for https://parkaccess.com.ph/products.json
[21:15:15.003] [ERROR]  INIT ERR @ https://parkaccess.com.ph: Cannot read property 'products' of undefined

and so on and so forth... It doesnt stop. what seems to be the problem there? 

i can send you a screen shot of what shows up

**Comment by mgundle302** [comment]
Receiving this error for multiple sites:

MON ERR @ https://www.undefeated.com: this.currentProducts is not iterable

Not sure how to correct this error and to have the bot send webhooks or add keywords to monitor

**Comment by aarock1234** [comment]
> monitor for https://parkaccess.com.ph/ does not work
> it just shows this:
> [21:15:14.624] [LOG] Monitor Started for https://parkaccess.com.ph/products.json
> [21:15:15.003] [ERROR] INIT ERR @ https://parkaccess.com.ph: Cannot read property 'products' of undefined
> 
> and so on and so forth... It doesnt stop. what seems to be the problem there?
> 
> i can send you a screen shot of what shows up

Don't add "products.json" to the end inside the site TXT.
