### ISSUE TITLE
Error Tunneling Socket

### ISSUE THREAD

**Issue by hamim23z** [aarock1234/shopify-monitor#3]
Hey. It's me again. So I saw that I had the wrong thing yesterday. So I uninstalled everything today, and tried again. I saw all the correct folders and did everything properly. But, when I typed "npm start", it says error tunneling socket and then it keeps repeating that. What should I do to fix this? I'm on Mac OS. 
<img width="1440" alt="Screen Shot 2020-11-24 at 3 52 50 PM" src="https://user-images.githubusercontent.com/74880822/100150088-1e52fc00-2e6d-11eb-93a5-65e0adac4b9f.png">

**Comment by hamim23z** [comment]
So after I asked a few people they said that it was error 407, and I need proxy authentication

**Comment by aarock1234** [comment]
That is a proxy error. You also realize that finishline nor footlocker is Shopify, right?
