### ISSUE TITLE
iterable  prodduct

### ISSUE THREAD

**Issue by Andrew870** [aarock1234/shopify-monitor#4]
MON ERR @ https://example.de : this.currentProducts is not iterable what this means ?
?????

**Comment by aarock1234** [comment]
https://example.de is not even a real domain, let alone a **Shopify** store. 

Closed.

**Comment by Andrew870** [comment]
i need to bot this https://deviceone.gr/

Στις Τετ, 23 Δεκ 2020 στις 12:15 π.μ., ο/η Rock <notifications@github.com>
έγραψε:

**Comment by Andrew870** [comment]
> https://example.de is not even a real domain, let alone a **Shopify** store.
> 
> Closed.
Reply:

not its not that i just dont want to expose the sitte
