### ISSUE TITLE
ERROR  WEBHOOK: Cannot read property 'src' of undefined

### ISSUE THREAD

**Issue by HonroAvispa0001** [aarock1234/shopify-monitor#7]
This appears randomly, it just appear at any moment, sometimes at the beggining of the script, and somethings a lot of time time later the script has been running

**Comment by aarock1234** [comment]
That means a restock was picked up, but your webhook is setup incorrectly.

**Comment by aarock1234** [comment]
Actually, this is a bug with the code. I will fix it ASAP 👍🏽

**Comment by ghost** [comment]
I’ll been pending, and congrats for this monitor, I’ve tried other ones and this works better than any other

**Comment by Noodleyy** [comment]
Still seems to be happening and I can't seem to understand fully why. As @HonroAvisp has mentioned it occurs randomly and I can't seem to replicate it and get the reasoning behind it.

**Comment by aarock1234** [comment]
Fixed this in the recent update, delete all files and follow the instructions starting from step 3.
